# 服务器端口
server:
  port: 8081

# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xy_oa?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zxcvbnm123
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
        enabled: true
        profile-enable: true
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 300ms

# mybatis 文件配置
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

